language: node_js
node_js:
    - "10"
notifications:
    email: false
branches:
  only:
  - master
deploy:
  - provider: npm
    email: "rene.heinen@gmx.net"
    api_key: $NPM_TOKEN
    skip_cleanup: true