language: node_js
node_js:
  - '10'
install:
  - npm i
script:
  - npm run test
  - npm run build
cache:
  directories:
    - 'node_modules'
notifications:
  email: false
branches:
  only:
    - master
    - develop
deploy:
  - provider: npm
    email: 'rene.heinen@gmx.net'
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      branch: master
